### ISSUE TITLE
Module '"@egoist/tipc/renderer"' has no exported member 'createHandlers'.

### ISSUE THREAD

**Issue by STRRL** [egoist/tipc#7]
it seems tipc does not support "Calling renderer from main" on the latest release

or I missed something? 

https://github.com/egoist/tipc/tree/main?tab=readme-ov-file#calling-renderer-from-main

**Comment by kingyue737** [comment]
There are some errors in the docs. I've opened a PR #6 to fix it.

```ts
import { createEventHandlers } from "@egoist/tipc/renderer"
```
